from __future__ import annotations

from io import BytesIO
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)
from reportlab.pdfgen import canvas


def _footer_canvas(c: canvas.Canvas, doc: SimpleDocTemplate):
    """Adds footer with page number + generated timestamp."""
    c.saveState()
    c.setFont("Helvetica", 9)
    page_num = c.getPageNumber()
    txt_left = "Generated by Meal Recommender"
    txt_right = f"Page {page_num}"
    c.setFillColor(colors.grey)

    c.drawString(18 * mm, 12 * mm, txt_left)
    c.drawRightString(A4[0] - 18 * mm, 12 * mm, txt_right)
    c.restoreState()


def build_daily_plan_pdf(
    *,
    plan_date: str,
    plan: Dict[str, Any],
    items: List[Dict[str, Any]],
    facility_name: str = "Care Home Kitchen Order Sheet",
) -> BytesIO:
    """
    Build a professional PDF for the daily plan.

    Expected `items` element shape (what your daily_plan_view passes):
      {
        "meal_type": "breakfast"|"lunch"|"dinner"|"snack",
        "resident": Resident|None,
        "meal": Meal|None,
        "original_meal": Meal|None,
        "is_overridden": bool,
        "ml_score": float|None,
        "reason": str|None,
      }
    """
    buf = BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=18 * mm,
        title=f"Daily Meal Plan {plan_date}",
        author="Meal Recommender",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleCustom",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        spaceAfter=6,
    )
    sub_style = ParagraphStyle(
        "SubCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=13,
        textColor=colors.HexColor("#444444"),
    )
    h_style = ParagraphStyle(
        "HCustom",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=14,
        spaceBefore=10,
        spaceAfter=6,
    )
    cell_style = ParagraphStyle(
        "Cell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=11,
    )
    cell_bold = ParagraphStyle(
        "CellBold",
        parent=cell_style,
        fontName="Helvetica-Bold",
    )
    small_grey = ParagraphStyle(
        "SmallGrey",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=10,
        textColor=colors.HexColor("#666666"),
    )

    # ---- Header ----
    status = (plan or {}).get("status", "draft")
    strict = (plan or {}).get("strict", True)
    created_at = (plan or {}).get("created_at")
    fulfilled_at = (plan or {}).get("fulfilled_at")

    generated_ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    story: List[Any] = []
    story.append(Paragraph(facility_name, title_style))
    story.append(
        Paragraph(
            f"<b>Date:</b> {plan_date} &nbsp;&nbsp; "
            f"<b>Status:</b> {status.capitalize()} &nbsp;&nbsp; "
            f"<b>Rules:</b> {'Strict' if strict else 'Relaxed'}",
            sub_style,
        )
    )

    meta_line_parts = []
    if created_at:
        meta_line_parts.append(f"<b>Plan created:</b> {created_at}")
    meta_line_parts.append(f"<b>PDF generated:</b> {generated_ts}")
    if fulfilled_at:
        meta_line_parts.append(f"<b>Fulfilled at:</b> {fulfilled_at}")

    story.append(Paragraph(" &nbsp;&nbsp; · &nbsp;&nbsp; ".join(meta_line_parts), sub_style))
    story.append(Spacer(1, 8))

    # ---- Pivot items: resident -> meal_type -> meal display ----
    # We want one row per resident with 4 columns for meal types.
    # Also keep flags for overrides.
    residents_map: Dict[str, Dict[str, Any]] = {}
    for it in items:
        res = it.get("resident")
        if not res:
            continue
        rid = getattr(res, "resident_id", None) or "unknown"
        if rid not in residents_map:
            residents_map[rid] = {
                "resident": res,
                "breakfast": None,
                "lunch": None,
                "dinner": None,
                "snack": None,
                "override_flags": {"breakfast": False, "lunch": False, "dinner": False, "snack": False},
            }

        mt = (it.get("meal_type") or "").lower().strip()
        meal = it.get("meal")
        if mt in {"breakfast", "lunch", "dinner", "snack"}:
            residents_map[rid][mt] = it
            residents_map[rid]["override_flags"][mt] = bool(it.get("is_overridden"))

    # Sort residents by name
    residents_list = sorted(
        residents_map.values(),
        key=lambda x: (getattr(x["resident"], "name", "") or "").lower(),
    )

    # ---- Summary box ----
    total_residents = len(residents_list)
    total_items = len(items)
    missing = sum(1 for it in items if it.get("meal") is None)
    overrides = sum(1 for it in items if it.get("is_overridden"))

    summary_table = Table(
        [
            [
                Paragraph("<b>Summary</b>", cell_bold),
                Paragraph(f"Residents: <b>{total_residents}</b>", cell_style),
                Paragraph(f"Total slots: <b>{total_items}</b>", cell_style),
                Paragraph(f"Unfilled slots: <b>{missing}</b>", cell_style),
                Paragraph(f"Overrides: <b>{overrides}</b>", cell_style),
            ]
        ],
        colWidths=[28 * mm, 38 * mm, 38 * mm, 45 * mm, 33 * mm],
    )
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F3F5F7")),
                ("BOX", (0, 0), (-1, 0), 0.6, colors.HexColor("#D6DADF")),
                ("INNERGRID", (0, 0), (-1, 0), 0.3, colors.HexColor("#D6DADF")),
                ("VALIGN", (0, 0), (-1, 0), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, 0), 8),
                ("RIGHTPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 6),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 10))

    # ---- Main table ----
    story.append(Paragraph("Meal Order Table", h_style))

    header = [
        Paragraph("<b>Resident</b>", cell_bold),
        Paragraph("<b>Diet</b>", cell_bold),
        Paragraph("<b>Breakfast</b>", cell_bold),
        Paragraph("<b>Lunch</b>", cell_bold),
        Paragraph("<b>Dinner</b>", cell_bold),
        Paragraph("<b>Snack</b>", cell_bold),
    ]
    data: List[List[Any]] = [header]

    def fmt_meal_cell(it: Optional[Dict[str, Any]]) -> Paragraph:
        if not it or not it.get("meal"):
            return Paragraph("<font color='#777777'>—</font>", cell_style)

        meal = it["meal"]
        name = getattr(meal, "name", "Unnamed meal")
        kcal = getattr(meal, "calories_kcal", None)
        prot = getattr(meal, "protein_g", None)
        na = getattr(meal, "sodium_mg", None)

        overridden = bool(it.get("is_overridden"))
        tag = ""
        if overridden:
            tag = " <font color='#0B6FA4'>(Override)</font>"

        # Keep it compact but informative
        line2_parts = []
        if kcal is not None:
            line2_parts.append(f"{float(kcal):.0f} kcal")
        if prot is not None:
            line2_parts.append(f"P {float(prot):.1f}g")
        if na is not None:
            line2_parts.append(f"Na {float(na):.0f}mg")

        line2 = " · ".join(line2_parts)
        html = f"<b>{name}</b>{tag}"
        if line2:
            html += f"<br/><font color='#555555'>{line2}</font>"
        return Paragraph(html, cell_style)

    for row in residents_list:
        res = row["resident"]
        name = getattr(res, "name", "Unknown")
        age = getattr(res, "age", None)
        diet = getattr(res, "diet_type", None) or "none"

        resident_cell = f"<b>{name}</b>"
        if age is not None:
            resident_cell += f"<br/><font color='#666666'>Age {age}</font>"

        data.append(
            [
                Paragraph(resident_cell, cell_style),
                Paragraph(str(diet).capitalize(), cell_style),
                fmt_meal_cell(row.get("breakfast")),
                fmt_meal_cell(row.get("lunch")),
                fmt_meal_cell(row.get("dinner")),
                fmt_meal_cell(row.get("snack")),
            ]
        )

    # Column widths tuned for A4 landscape-like density in portrait
    col_widths = [38 * mm, 18 * mm, 34 * mm, 34 * mm, 34 * mm, 34 * mm]
    table = Table(data, colWidths=col_widths, repeatRows=1)

    table_style = TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F2A37")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D6DADF")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]
    )
    table.setStyle(table_style)

    story.append(table)
    story.append(Spacer(1, 10))

    # ---- Notes + signatures ----
    story.append(
        Paragraph(
            "Notes",
            h_style,
        )
    )
    story.append(
        Paragraph(
            "• Meals marked <font color='#0B6FA4'>(Override)</font> were manually changed by an administrator.<br/>"
            "• Unfilled slots are shown as — . Consider regenerating with relaxed rules or adding more meals.",
            small_grey,
        )
    )
    story.append(Spacer(1, 10))

    sig_table = Table(
        [
            [
                Paragraph("<b>Kitchen lead signature:</b> ____________________", cell_style),
                Paragraph("<b>Time prepared:</b> ____________", cell_style),
            ],
            [
                Paragraph("<b>Admin signature:</b> ____________________", cell_style),
                Paragraph("<b>Time served:</b> ____________", cell_style),
            ],
        ],
        colWidths=[90 * mm, 80 * mm],
    )
    sig_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#D6DADF")),
                ("INNERGRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D6DADF")),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFFFFF")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )
    story.append(KeepTogether(sig_table))

    doc.build(story, onFirstPage=_footer_canvas, onLaterPages=_footer_canvas)
    buf.seek(0)
    return buf
